""" 
    Checklist Constants 
"""
CHECKLIST_ATTRIB_COL = "spalte"
CHECKLIST_ATTRIB_ROW = "zeile"
CHECKLIST_ATTRIB_TAB = "tabelle"
CHECKLIST_ATTRIB_TITLE = "titel"
CHECKLIST_ATTRIB_VERSION = "version"
CHECKLIST_ATTRIB_WORDTYPE = "wordType"
CHECKLIST_ATTRIB_WORDTYPE_TABLE = "table"

""" 
    DSE Document Constants 
"""
DSEDOC_ATTRIB_TITLE = "titel"
DSEDOC_ATTRIB_VERSION = "version"
DSEDOC_TAG_CHAPTER = "Kapitel"
DSEDOC_TAG_PARAGRAPH = "Abschnitt"